(function(t){t.BALT||(t.BALT={}),t.BALT.gallery=function(e,i){var n=this,o=e,s=o.find(".gallery-container")
n.settings={loader:!1,ratioResize:!0,animating:!1,itemWidth:s.width(),slideCount:s.find(".slide").length,loadCounter:0,newTop:0,origHeighttext:0,origToptext:0,direction:1,ratio:0},n.settings=t.extend(n.settings,i),console.log("root.settings: ",n.settings),n.init=function(){if(n.settings.loader){var e=o.find(".slide")
e.each(function(){registerImgFileSize(this.src),(t(this)[0].complete||4==t(this)[0].readyState)&&l(),t(this).load(l)})}else r()
n.settings.ratio=s.find(".slide:eq(0)").height()/s.find(".slide:eq(0)").width(),console.log(""),console.log("target ",o),console.log("ratioResize ",n.settings.ratioResize),d()}
var d=function(){t(window).resize(g),g(),t(".next").click(function(t){t.preventDefault()}),t(".previous").click(function(t){t.preventDefault()}),t(document).keydown(f)},l=function(){try{n.settings.loadCounter++,n.settings.loadCounter==n.settings.slideCount-1&&(r(),g())}catch(t){}},r=function(){t(".slide").each(function(){})},g=function(){s.find(".slide").each(function(){t(this).width(o.width()),console.log(".ratioResize: ",n.settings.ratioResize),n.settings.ratioResize&&(t(this).height(Math.round(o.width()*n.settings.ratio)),t(this).height()<o.height()&&(t(this).height(o.height()),t(this).width(Math.round(o.height()/n.settings.ratio))))}),n.settings.itemWidth=s.find(".slide:eq(0)").width(),totalImagesWidth=n.settings.slideCount*n.settings.itemWidth,console.log("root.settings.itemWidth : ",n.settings.itemWidth,totalImagesWidth),s.width(totalImagesWidth),s.css("left",-n.settings.itemWidth)}
n.gotoIterativeIndex=function(t){console.log("gotoIterativeIndex ",n.settings.itemWidth,n.settings.animating),n.settings.animating||(n.settings.direction=t,n.settings.animating=!0,1==t?(console.log("$container.find( '.slide' ).first(): ",s.find(".slide").first()),s.find(".slide").first().remove().css("z-index","1").appendTo(s),s.css({left:0})):-1==t&&(s.find(".slide").last().remove().css("z-index","2").prependTo(s),s.css({left:-2*n.settings.itemWidth})),s.find(".slide:eq(1)").css("z-index","0"),c(-1*n.settings.itemWidth,a))},n.next=function(){console.log("NEXT: ",s.find(".slide")),n.gotoIterativeIndex(1)},n.previous=function(){console.log("PREVIOUS: ",s.find(".slide")),n.gotoIterativeIndex(-1)}
var a=function(){n.settings.animating=!1,h()},c=function(t,e){s.animate({left:t},{duration:500,complete:e})},h=function(){t(".slide:eq(1)").find(".slideLinks").fadeIn()},f=function(t){return 37==t.keyCode?(console.log("nxt"),n.gotoIterativeIndex(1),!1):39==t.keyCode?(console.log("prev"),n.gotoIterativeIndex(-1),!1):void 0}},t.BALT.controls=function(e,i){var n=e,o={}
o=t.extend(o,i)
var s=function(){n.on("click",".next",d),n.on("click",".previous",l)},d=function(t){t.preventDefault()
for(var e=0;o.toControl.length>e;e++)o.toControl[e].next()},l=function(t){t.preventDefault()
for(var e=0;o.toControl.length>e;e++)o.toControl[e].previous(),console.log("settings.toControl[i]: ",o.toControl[e])}
s()}})(jQuery)
