(function(t){t.BALT||(t.BALT={}),t.BALT.gallery=function(i,e){var n=this,o=i,s=o.find(".gallery-container")
n.settings={loader:!1,ratioResize:!0,animating:!1,itemWidth:s.width(),slideCount:s.find(".slide").length,loadCounter:0,newTop:0,origHeighttext:0,origToptext:0,direction:1,ratio:0},n.settings=t.extend(n.settings,e),n.init=function(){if(n.settings.loader){var i=o.find(".slide")
i.each(function(){registerImgFileSize(this.src),(t(this)[0].complete||4==t(this)[0].readyState)&&r(),t(this).load(r)})}else l()
n.settings.ratio=s.find(".slide:eq(0)").height()/s.find(".slide:eq(0)").width(),d()}
var d=function(){t(window).resize(a),a(),t(".next").click(function(t){t.preventDefault()}),t(".previous").click(function(t){t.preventDefault()}),t(document).keydown(h)},r=function(){try{n.settings.loadCounter++,n.settings.loadCounter==n.settings.slideCount-1&&(l(),a())}catch(t){}},l=function(){t(".slide").each(function(){})},a=function(){s.find(".slide").each(function(){t(this).width(o.width()),n.settings.ratioResize&&(t(this).height(Math.round(o.width()*n.settings.ratio)),t(this).height()<o.height()&&(t(this).height(o.height()),t(this).width(Math.round(o.height()/n.settings.ratio))))}),n.settings.itemWidth=s.find(".slide:eq(0)").width(),totalImagesWidth=n.settings.slideCount*n.settings.itemWidth,s.width(totalImagesWidth),s.css("left",-n.settings.itemWidth)}
n.gotoIterativeIndex=function(t){n.settings.animating||(n.settings.direction=t,n.settings.animating=!0,1==t?(console.log("$container.find( '.slide' ).first(): ",s.find(".slide").first()),s.find(".slide").first().remove().css("z-index","1").appendTo(s),s.css({left:0})):-1==t&&(s.find(".slide").last().remove().css("z-index","2").prependTo(s),s.css({left:-2*n.settings.itemWidth})),s.find(".slide:eq(1)").css("z-index","0"),g(-1*n.settings.itemWidth,c))},n.next=function(){n.gotoIterativeIndex(1)},n.previous=function(){n.gotoIterativeIndex(-1)}
var c=function(){n.settings.animating=!1,f()},g=function(t,i){s.animate({left:t},{duration:500,complete:i})},f=function(){t(".slide:eq(1)").find(".slideLinks").fadeIn()},h=function(t){return 37==t.keyCode?(console.log("nxt"),n.gotoIterativeIndex(1),!1):39==t.keyCode?(console.log("prev"),n.gotoIterativeIndex(-1),!1):void 0}},t.BALT.controls=function(i,e){var n=i,o={}
o=t.extend(o,e)
var s=function(){n.on("click",".next",d),n.on("click",".previous",r)},d=function(t){t.preventDefault()
for(var i=0;o.toControl.length>i;i++)o.toControl[i].next()},r=function(t){t.preventDefault()
for(var i=0;o.toControl.length>i;i++)o.toControl[i].previous(),console.log("settings.toControl[i]: ",o.toControl[i])}
s()}})(jQuery)
